<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SEWindows.Server</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Fido2" Version="4.0.1" />
    <PackageReference Include="Fido2.AspNet" Version="4.0.1" />
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.5.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.0-preview.4.25258.110" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" Version="10.0.0-preview.4.25258.110" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="IncludedCACertificateReportForMSFT.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
